resources:
  - name: learn.concourse.docker
    type: git
    source:
      uri: git@github.com:tankanow/learn.concourse.docker.git
      branch: master
      private_key: {{tankanow-github-private-key}}

  - name: learn.concourse.docker-image
    type: docker-image
    source:
      repository: atankanow/learn.concourse.docker-image
      email: {{docker-email}}
      name: {{docker-username}}
      password: {{docker-password}}

jobs:
  - name: build-push-image
    plan:
      - get: learn.concourse.docker
        trigger: true
      - put: learn.concourse.docker-image
        params: {build: learn.concourse.docker}
  - name: docker-version
    plan:
      - get: learn.concourse.docker
        trigger: true
      - task: print-version
        file: ci/docker-version.yml
